[package]
name = "common-streams"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = {path = "../arrow"}
common-datablocks = {path = "../datablocks"}
common-datavalues = {path = "../datavalues"}
common-functions = {path = "../functions"}

# Github dependencies

# Crates.io dependencies
anyhow = "1.0.40"
crossbeam = "0.8"
futures = "0.3"
tokio = { version = "1.5", features = ["macros", "rt","rt-multi-thread", "sync"] }

[dev-dependencies]
pretty_assertions = "0.7"
